#Archivo para declarar constantes de la aplicacion

TITULO_INTERFAZ = "Othello"
TITULO = "OTHELLO"

#Dimensiones
VENTANA_LARGO = 700 
VENTANA_ANCHO = 1100

ORIGEN_MARGO = {'x':30,'y':30}
ORIGEN_TABLERO = {'x':117,'y':117}
FIN_MARCO = {'x':667,'y':667}
FIN_TABLERO = {'x':583,'y':583}
DIM_TABLERO = FIN_TABLERO['x']-ORIGEN_TABLERO['x']
CELDAS = 8
DIM_CELDA = DIM_TABLERO / CELDAS
DIM_FICHA = DIM_CELDA
LOCALIZACION_CENTRO_DERECHA =  FIN_MARCO['x'] + ((VENTANA_ANCHO - FIN_MARCO['x']) //2 )
DIM_TAPA_TEXTO = {'x':200,'y':45}

#Turno 
TURNO = "TURNO:"
DIM_FICHA_TURNO = DIM_FICHA/1.5

#Movimientos
INICIO_TEXTO_MOVIMIENTOS = {"x": LOCALIZACION_CENTRO_DERECHA, "y":ORIGEN_MARGO['y'] + 50}
DISTANCIA_TEXTO_MOVIMIENTOS = 25
DIM_FICHA_MOVIMIENTO = DIM_FICHA_TURNO/1.5
OFFSET_UNO_MOVIMIENTO = -80
OFFSET_DOS_MOVIMIENTO = 50
OFFSET_TRES_MOVIMIENTO = 180
MAXIMO_MOVIMIENTOS_TEXTO = 20
SEPARACION_FICHA_TEXTO = 100

#Fuentes
FUENTE = "../Fuentes/KarmaSuture.ttf"
FUENTE_TITULO = "../Fuentes/KarmaSuture.ttf"
ESPACIADO_TITULO = 2
ESPACIADO_TURNO = 1
ESPACIADO_GANADOR = 1
ESPACIADO_BOTONES = 1
ESPACIADO_MOVIMIENTOS = 1

#Imagenes
IMG_TABLERO = "../Assets/Board-othello.png"
IMG_FICHA_BLANCA = "../Assets/Pieza-blanca.png"
IMG_FICHA_NEGRA = "../Assets/Pieza-negra.png"
IMG_FONDO_MENU_PRINCIPAL = "../Assets/Fondo-Menu-Tablero.png"
IMG_FONDO_JUEGO = "../Assets/Fondo-Menu.png"
IMG_BOTON = "../Assets/Boton.png"
IMG_BOTON_ENCIMA = "../Assets/Boton-Encima.png"
IMG_TAPA_TEXTO = "../Assets/Tapar-Texto.png"

#Botones
ANCHURA_BOTON = 250
ALTURA_BOTON = 100
ANCHURA_BOTON_GUARDADO = 250
ALTURA_BOTON_GUARDADO = 70
TEXTO_BOTON_IA = "1 VS IA"
TEXTO_BOTON_JUGADORES = "1 VS 1"
TEXTO_BOTON_GUARDADO = "GUARDAR RESULTADO"

#Colores RGB
BLANCO_RGB = (255,255,255)
NEGRO_RGB = (0,0,0)
MARRON_RGB = (104,68,53)
VERDE_RGB = (45,86,50)

#Jugadores
BLANCO = 2
NEGRO = 1
P1 = 1
P2 = 2

#Tablero 
VACIO = 0
CASILLAS_TABLERO = 64
VALOR_COLUMNAS = {"0":"A","1":"B","2":"C","3":"D","4":"E","5":"F","6":"G","7":"H"}
VALOR_FILAS = {"0":"8","1":"7","2":"6","3":"5","4":"4","5":"3","6":"2","7":"1"}
A = 0
B = 1
C = 2
D = 3
E = 4
F = 5
G = 6 
H = 7

#Ganador
BLANCAS = "GANAN BLANCAS"
NEGRAS = "GANAN NEGRAS"
EMPATE = "EMPATE"
JUGADOR1_GANA = 1
JUGADOR2_GANA = 2
EMPATE_ENTRE_JUGADORES = 0
